WEAPONS = {
    [`WEAPON_UNARMED`]          = { "Le patient à été frappé",                                      "Frappé" },
    [`WEAPON_KNIFE`]            = { "Le patient à été poignardé",                                   "Poignardé par un objet tranchant" },
    [`WEAPON_NIGHTSTICK`]       = { "Le patient à été frappé avec une matraque",                    "Frappé par un objet lourd" },
    [`WEAPON_HAMMER`]           = { "Le patient a été frappé avec un marteau",                      "Poignardé par un objet lourd" },
    [`WEAPON_BAT`]              = { "Le patient a été frappé avec une batte",                       "Frappé par un objet lourd" },
    [`WEAPON_GOLFCLUB`]         = { "Le patient a été frappé avec un club de golf",                 "Frappé par un objet" },
    [`WEAPON_CROWBAR`]          = { "Le patient a été frappé avec un pied de biche",                "Poignardé par un objet" },
    [`WEAPON_PISTOL`]           = { "Le patient à été touché par des balles de calibre 9mm",        "Par balle de calibre 9mm" },
    [`WEAPON_COMBATPISTOL`]     = { "Le patient à été touché par des balles de calibre 9mm",        "Par balle de calibre 9mm" },
    [`WEAPON_APPISTOL`]         = { "Le patient à été touché par des balles de calibre 9mm",        "Par balle de calibre 9mm" },
    [`WEAPON_PISTOL50`]         = { "Le patient à été touché par des balles de calibre 50 AE",      "Par balle de calibre 50 AE" },
    [`WEAPON_MICROSMG`]         = { "Le patient à été touché par des balles de calibre 45 ACP",     "Par balle de calibre 45 ACP" },
    [`WEAPON_SMG`]              = { "Le patient à été touché par des balles de calibre 9mm",        "Par balle de calibre 9mm" },
    [`WEAPON_ASSAULTSMG`]       = { "Le patient à été touché par des balles de calibre 5.56x45",    "Par balle de calibre 5.56x45" },
    [`WEAPON_ASSAULTRIFLE`]     = { "Le patient à été touché par des balles de calibre 7.62x39",    "Par balle de calibre 7.62x39" },
    [`WEAPON_CARBINERIFLE`]     = { "Le patient à été touché par des balles de calibre 5.56x45",    "Par balle de calibre 5.56x45" },
    [`WEAPON_ADVANCEDRIFLE`]    = { "Le patient à été touché par des balles de calibre 5.56x45",    "Par balle de calibre 5.56x45" },
    [`WEAPON_MG`]               = { "Le patient à été touché par des balles de calibre 7.62x39",    "Par balle de calibre 7.62x39" },
    [`WEAPON_COMBATMG`]         = { "Le patient à été touché par des balles de calibre 5.56x45",    "Par balle de calibre 5.56x45" },
    [`WEAPON_PUMPSHOTGUN`]      = { "Le patient à été touché par des balles de calibre Gauge 12",   "Par balle de calibre Gauge 12" },
    [`WEAPON_SAWNOFFSHOTGUN`]   = { "Le patient à été touché par des balles de calibre Gauge 12",   "Par balle de calibre Gauge 12" },
    [`WEAPON_ASSAULTSHOTGUN`]   = { "Le patient à été touché par des balles de calibre Gauge 12",   "Par balle de calibre Gauge 12" },
    [`WEAPON_BULLPUPSHOTGUN`]   = { "Le patient à été touché par des balles de calibre Gauge 12",   "Par balle de calibre Gauge 12" },
    [`WEAPON_SNIPERRIFLE`]      = { "Le patient à été touché par des balles de calibre 7.62x51",    "Par balle de calibre 7.62x51" },
    [`WEAPON_HEAVYSNIPER`]      = { "Le patient à été touché par des balles de calibre 50 BMG",     "Par balle de calibre 50 BMG" },
    [`WEAPON_MOLOTOV`]          = { "Le patient à été brûlé par un objet inflamable",               "Brûlé par un objet inflamable" },
    [`weapon_stungun`]          = { "Le patient à pris un coup de jus",                             "Brûlé par un coup de jus" },

    [-842959696]                = { "Le patient à fait une grosse chute",                           "Chute" },
    [-1553120962]               = { "A été renversé par une voiture",                               "Choc de voiture" },
}

-- © 𝐴𝑟𝑖𝑢𝑠 𝐷𝑒𝑣𝑒𝑙𝑜𝑝𝑚𝑒𝑛𝑡
